### ISSUE TITLE
Swapped colors in the README file

### ISSUE THREAD

**Issue by danirod** [wuelnerdotexe/vscode-enfocado#1]
The color labels for bright yellow and bright green in the README table seems to be swapped. If you paste the values for these rows on a color picker, the "bright yellow" label actually makes bright green and the "bright green" label actually makes bright yellow.

https://github.com/wuelnerdotexe/vscode-enfocado/blob/600cfb8ab534dcd8e886d488086290a9382d19be/README.md?plain=1#L62-L63

This is what I get after pasting the colors on GIMP. Standard yellow and green colors are provided as a reference.

![imagen](https://user-images.githubusercontent.com/1568690/213924884-aa203c4d-300b-437b-9583-8c9c1aa10077.png)

**Comment by wuelnerdotexe** [comment]
Hi! @danirod - Thanks for submit this issue, I will correct it in the next update \0/

Saluditos.
